// <auto-generated />
using System;
using Clinic_Booking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clinic_Booking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250528112136_addSpecData")]
    partial class addSpecData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinic_Booking.Entities.Appointment.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Day.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 567, DateTimeKind.Local).AddTicks(762),
                            IsDeleted = false,
                            Name = "السبت",
                            NormalizedName = "Saturday"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 567, DateTimeKind.Local).AddTicks(795),
                            IsDeleted = false,
                            Name = "الاحد",
                            NormalizedName = "Sunday"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 567, DateTimeKind.Local).AddTicks(797),
                            IsDeleted = false,
                            Name = "الاثنين",
                            NormalizedName = "Monday"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 567, DateTimeKind.Local).AddTicks(798),
                            IsDeleted = false,
                            Name = "الثلاثاء",
                            NormalizedName = "Tuesday"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 567, DateTimeKind.Local).AddTicks(798),
                            IsDeleted = false,
                            Name = "الاربعاء",
                            NormalizedName = "Wednesday"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 567, DateTimeKind.Local).AddTicks(799),
                            IsDeleted = false,
                            Name = "الخميس",
                            NormalizedName = "Thursday"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 567, DateTimeKind.Local).AddTicks(800),
                            IsDeleted = false,
                            Name = "الجمعة",
                            NormalizedName = "Friday"
                        });
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Doctor.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("integer");

                    b.Property<int>("SubscriptionRank")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpecializationId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorAvailability.DoctorAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<int>("DayId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAppointments")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("DayId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DoctorAvailabilities");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorFeature.DoctorFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("FeatureId");

                    b.ToTable("DoctorFeature");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorSubscription.DoctorSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PackageId");

                    b.ToTable("DoctorSubscriptions");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Feature.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremiumOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Features");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Message.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Notification.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Payment.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Referral.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<int>("InvitedDoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("InviterDoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReferredAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvitedDoctorId");

                    b.HasIndex("InviterDoctorId");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Review.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Role.AspNetRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bf56622f-c2b0-4228-8d12-04268f738630"),
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2281),
                            IsDeleted = false,
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = new Guid("28dd0b27-8929-4d5c-956d-70537bd756d3"),
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2294),
                            IsDeleted = false,
                            Name = "NormalUser",
                            NormalizedName = "NORMALUSER"
                        },
                        new
                        {
                            Id = new Guid("bb3f3792-b4e8-460f-a977-3d95029cbb6c"),
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2296),
                            IsDeleted = false,
                            Name = "DoctorUser",
                            NormalizedName = "DOCTORUSER"
                        });
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Specialization.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2520),
                            IsDeleted = false,
                            Name = "أخصائي باطنية",
                            NormalizedName = "Internal Medicine Specialist"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2522),
                            IsDeleted = false,
                            Name = "أخصائي أنف وأذن وحنجرة",
                            NormalizedName = "ENT Specialist (Ear, Nose, and Throat)"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2523),
                            IsDeleted = false,
                            Name = "أخصائي قلب",
                            NormalizedName = "Cardiologist"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2524),
                            IsDeleted = false,
                            Name = "أخصائي عيون",
                            NormalizedName = "Ophthalmologist"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2525),
                            IsDeleted = false,
                            Name = "أخصائي جلدية",
                            NormalizedName = "Dermatologist"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2526),
                            IsDeleted = false,
                            Name = "أخصائي أعصاب",
                            NormalizedName = "Neurologist"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2527),
                            IsDeleted = false,
                            Name = "أخصائي جراحة عامة",
                            NormalizedName = "General Surgeon"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2629),
                            IsDeleted = false,
                            Name = "أخصائي جراحة عظام",
                            NormalizedName = "Orthopedic Surgeon"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2630),
                            IsDeleted = false,
                            Name = "أخصائي نسائية وتوليد",
                            NormalizedName = "Obstetrician-Gynecologist (OB-GYN)"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2632),
                            IsDeleted = false,
                            Name = "أخصائي أطفال",
                            NormalizedName = "Pediatrician"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2633),
                            IsDeleted = false,
                            Name = "أخصائي أورام",
                            NormalizedName = "Oncologist"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2634),
                            IsDeleted = false,
                            Name = "أخصائي كلى",
                            NormalizedName = "Nephrologist"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2635),
                            IsDeleted = false,
                            Name = "أخصائي جهاز هضمي",
                            NormalizedName = "Gastroenterologist"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2636),
                            IsDeleted = false,
                            Name = "أخصائي غدد صماء",
                            NormalizedName = "Endocrinologist"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2638),
                            IsDeleted = false,
                            Name = "أخصائي جراحة تجميل",
                            NormalizedName = "Plastic Surgeon"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2640),
                            IsDeleted = false,
                            Name = "أخصائي جراحة دماغ وأعصاب",
                            NormalizedName = "Neurosurgeon"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2641),
                            IsDeleted = false,
                            Name = "أخصائي تخدير",
                            NormalizedName = "Anesthesiologist"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2643),
                            IsDeleted = false,
                            Name = "أخصائي طب الأسرة",
                            NormalizedName = "Family Medicine Specialist"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2644),
                            IsDeleted = false,
                            Name = "أخصائي الطب النفسي",
                            NormalizedName = "Psychiatrist"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2645),
                            IsDeleted = false,
                            Name = "أخصائي أمراض معدية",
                            NormalizedName = "Infectious Disease Specialist"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2646),
                            IsDeleted = false,
                            Name = "أخصائي أشعة",
                            NormalizedName = "Radiologist"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2648),
                            IsDeleted = false,
                            Name = "أخصائي طب طوارئ",
                            NormalizedName = "Emergency Medicine Specialist"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2649),
                            IsDeleted = false,
                            Name = "أخصائي روماتيزم",
                            NormalizedName = "Rheumatologist"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2649),
                            IsDeleted = false,
                            Name = "أخصائي صدرية",
                            NormalizedName = "Pulmonologist"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2650),
                            IsDeleted = false,
                            Name = "أخصائي طب مهني",
                            NormalizedName = "Occupational Medicine Specialist"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2651),
                            IsDeleted = false,
                            Name = "أخصائي طب رياضي",
                            NormalizedName = "Sports Medicine Specialist"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2652),
                            IsDeleted = false,
                            Name = "أخصائي أمراض الدم",
                            NormalizedName = "Hematologist"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2655),
                            IsDeleted = false,
                            Name = "أخصائي علاج طبيعي",
                            NormalizedName = "Physiotherapist"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2656),
                            IsDeleted = false,
                            Name = "أخصائي تغذية",
                            NormalizedName = "Nutritionist"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(2656),
                            IsDeleted = false,
                            Name = "أخصائي نطق وتخاطب",
                            NormalizedName = "Speech Therapist"
                        });
                });

            modelBuilder.Entity("Clinic_Booking.Entities.SubscriptionPackage.SubscriptionPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<bool>("EBooking")
                        .HasColumnType("boolean");

                    b.Property<bool>("EPayments")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("MakeOffers")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxActiveOffers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDailyAppointments")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWeeklyDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<bool>("ShowMessages")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowReviews")
                        .HasColumnType("boolean");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(6798),
                            EBooking = false,
                            EPayments = false,
                            IsDeleted = false,
                            MakeOffers = false,
                            MaxActiveOffers = 0,
                            MaxDailyAppointments = 15,
                            MaxWeeklyDays = 4,
                            Name = "أساسي",
                            NormalizedName = "Basic",
                            Price = 0m,
                            ShowMessages = false,
                            ShowReviews = false,
                            YearlyPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(6804),
                            EBooking = false,
                            EPayments = false,
                            IsDeleted = false,
                            MakeOffers = false,
                            MaxActiveOffers = 0,
                            MaxDailyAppointments = 25,
                            MaxWeeklyDays = 5,
                            Name = "ذهبي",
                            NormalizedName = "Gold",
                            Price = 25m,
                            ShowMessages = false,
                            ShowReviews = true,
                            YearlyPrice = 250m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(6809),
                            EBooking = true,
                            EPayments = true,
                            IsDeleted = false,
                            MakeOffers = true,
                            MaxActiveOffers = 1,
                            MaxDailyAppointments = 35,
                            MaxWeeklyDays = 6,
                            Name = "ألماس",
                            NormalizedName = "Diamond ",
                            Price = 35m,
                            ShowMessages = true,
                            ShowReviews = true,
                            YearlyPrice = 350m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 5, 28, 14, 21, 36, 566, DateTimeKind.Local).AddTicks(6811),
                            EBooking = true,
                            EPayments = true,
                            IsDeleted = false,
                            MakeOffers = true,
                            MaxActiveOffers = 2,
                            MaxDailyAppointments = 1000,
                            MaxWeeklyDays = 7,
                            Name = "فاخر",
                            NormalizedName = "Premium",
                            Price = 45m,
                            ShowMessages = true,
                            ShowReviews = true,
                            YearlyPrice = 450m
                        });
                });

            modelBuilder.Entity("Clinic_Booking.Entities.User.AspNetUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d6f236d9-179c-4993-bf7e-3cd3d6b1bf64"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "22fbe6cc-20ae-40af-aa4e-9f43bc81961a",
                            CreatedAt = new DateTime(2025, 5, 28, 11, 21, 36, 527, DateTimeKind.Utc).AddTicks(7632),
                            EmailConfirmed = false,
                            IsDeleted = false,
                            IsFirstLogin = true,
                            IsLocked = false,
                            LastLoginDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "SUPARADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEFAxYEqOiTqX1Srsn3Ob545f0kBBphYaSRkHTPuE56GNf/NcT8j5izs6cMEzbDdNwA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a9a02fd6-2b99-4752-833f-f36351b8b54f",
                            TwoFactorEnabled = false,
                            UserName = "superadmin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Appointment.Appointment", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Doctor.Doctor", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Specialization.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Specialization");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorAvailability.DoctorAvailability", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Day.Day", "Day")
                        .WithMany()
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany("Availabilities")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Day");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorFeature.DoctorFeature", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany("DoctorFeatures")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.Feature.Feature", "Feature")
                        .WithMany("DoctorFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorSubscription.DoctorSubscription", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany("DoctorSubscriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.SubscriptionPackage.SubscriptionPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Message.Message", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Notification.Notification", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany("Notifications")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Payment.Payment", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Appointment.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Referral.Referral", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "InvitedDoctor")
                        .WithMany()
                        .HasForeignKey("InvitedDoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "InviterDoctor")
                        .WithMany()
                        .HasForeignKey("InviterDoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvitedDoctor");

                    b.Navigation("InviterDoctor");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Review.Review", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany("Reviews")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Role.AspNetRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Role.AspNetRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Doctor.Doctor", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("DoctorFeatures");

                    b.Navigation("DoctorSubscriptions");

                    b.Navigation("Notifications");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Feature.Feature", b =>
                {
                    b.Navigation("DoctorFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
