// <auto-generated />
using System;
using Clinic_Booking.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Clinic_Booking.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601210000_CompleteReviews")]
    partial class CompleteReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Clinic_Booking.Entities.Appointment.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CancelledByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<string>("GuestName")
                        .HasColumnType("text");

                    b.Property<string>("GuestPhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPhoneConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("PaymentAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("QueueNumber")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.HasIndex("ClinicId", "AppointmentDate", "QueueNumber")
                        .IsUnique();

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.BookingOtpRequest.BookingOtpRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("CodeSalt")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId", "IsUsed");

                    b.ToTable("BookingOtpRequests");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Clinic.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("IraqiProvince")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(9, 6)
                        .HasColumnType("numeric(9,6)");

                    b.Property<string>("MapUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("IraqiProvince", "IsVisible", "IsDeleted");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.ClinicException.ClinicException", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<string>("ClosureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("interval");

                    b.Property<DateTime>("ExceptionDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxAppointments")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId", "ExceptionDate")
                        .IsUnique()
                        .HasFilter("\"IsDeleted\" = false");

                    b.ToTable("ClinicExceptions");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Day.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Days");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 957, DateTimeKind.Local).AddTicks(3420),
                            IsDeleted = false,
                            Name = "السبت",
                            NormalizedName = "Saturday"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 957, DateTimeKind.Local).AddTicks(3470),
                            IsDeleted = false,
                            Name = "الاحد",
                            NormalizedName = "Sunday"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 957, DateTimeKind.Local).AddTicks(3472),
                            IsDeleted = false,
                            Name = "الاثنين",
                            NormalizedName = "Monday"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 957, DateTimeKind.Local).AddTicks(3473),
                            IsDeleted = false,
                            Name = "الثلاثاء",
                            NormalizedName = "Tuesday"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 957, DateTimeKind.Local).AddTicks(3474),
                            IsDeleted = false,
                            Name = "الاربعاء",
                            NormalizedName = "Wednesday"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 957, DateTimeKind.Local).AddTicks(3475),
                            IsDeleted = false,
                            Name = "الخميس",
                            NormalizedName = "Thursday"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 957, DateTimeKind.Local).AddTicks(3475),
                            IsDeleted = false,
                            Name = "الجمعة",
                            NormalizedName = "Friday"
                        });
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Doctor.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDay")
                        .HasColumnType("date");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IraqiProvince")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPubliclyVisible")
                        .HasColumnType("boolean");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<int>("SpecializationId")
                        .HasColumnType("integer");

                    b.Property<int>("SubscriptionRank")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName");

                    b.HasIndex("SpecializationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("IsPubliclyVisible", "SpecializationId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorAvailability.DoctorAvailability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<int>("DayId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAppointments")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("DayId");

                    b.ToTable("DoctorAvailabilities");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorFeature.DoctorFeature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("FeatureId");

                    b.ToTable("DoctorFeature");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorSubscription.DoctorSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<int>("PackageId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.HasIndex("DoctorId", "Status", "EndDate");

                    b.ToTable("DoctorSubscriptions");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Feature.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPremiumOnly")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 957, DateTimeKind.Local).AddTicks(5867),
                            Description = "",
                            IsDeleted = false,
                            IsPremiumOnly = true,
                            Name = "تفعيل التقييم والردود",
                            NormalizedName = "ShowReviews"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 957, DateTimeKind.Local).AddTicks(5875),
                            Description = "",
                            IsDeleted = false,
                            IsPremiumOnly = true,
                            Name = "تفعيل زر الرسائل",
                            NormalizedName = "ShowMessages"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 957, DateTimeKind.Local).AddTicks(5876),
                            Description = "",
                            IsDeleted = false,
                            IsPremiumOnly = true,
                            Name = "تفعيل الحجز الالكتروني",
                            NormalizedName = "EBooking"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 957, DateTimeKind.Local).AddTicks(5877),
                            Description = "",
                            IsDeleted = false,
                            IsPremiumOnly = true,
                            Name = "تفعيل الدفع الالكتروني",
                            NormalizedName = "EPayments"
                        });
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Message.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Notification.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<int?>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Payment.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Referral.Referral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<int>("InvitedDoctorId")
                        .HasColumnType("integer");

                    b.Property<int>("InviterDoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReferredAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("InvitedDoctorId");

                    b.HasIndex("InviterDoctorId");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Review.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppoinmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<int>("DoctorId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AppoinmentId")
                        .IsUnique()
                        .HasFilter("\"AppoinmentId\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("DoctorId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Reviews_Rating_Range", "\"Rating\" >= 1 AND \"Rating\" <= 5");
                        });
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Role.AspNetRoles", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c48a5065-5688-4be4-9681-58b5b56a08a7"),
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4199),
                            IsDeleted = false,
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = new Guid("8eee18ae-4581-49df-95e1-b2ca52e13a39"),
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4224),
                            IsDeleted = false,
                            Name = "NormalUser",
                            NormalizedName = "NORMALUSER"
                        },
                        new
                        {
                            Id = new Guid("aa044017-b326-4e6e-85c0-d131d1cbcb57"),
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4226),
                            IsDeleted = false,
                            Name = "DoctorUser",
                            NormalizedName = "DOCTORUSER"
                        });
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Specialization.Specialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Specializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4621),
                            IsDeleted = false,
                            Name = "أخصائي باطنية",
                            NormalizedName = "Internal Medicine Specialist"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4624),
                            IsDeleted = false,
                            Name = "أخصائي أنف وأذن وحنجرة",
                            NormalizedName = "ENT Specialist (Ear, Nose, and Throat)"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4626),
                            IsDeleted = false,
                            Name = "أخصائي قلب",
                            NormalizedName = "Cardiologist"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4626),
                            IsDeleted = false,
                            Name = "أخصائي عيون",
                            NormalizedName = "Ophthalmologist"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4627),
                            IsDeleted = false,
                            Name = "أخصائي جلدية",
                            NormalizedName = "Dermatologist"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4628),
                            IsDeleted = false,
                            Name = "أخصائي أعصاب",
                            NormalizedName = "Neurologist"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4629),
                            IsDeleted = false,
                            Name = "أخصائي جراحة عامة",
                            NormalizedName = "General Surgeon"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4630),
                            IsDeleted = false,
                            Name = "أخصائي جراحة عظام",
                            NormalizedName = "Orthopedic Surgeon"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4631),
                            IsDeleted = false,
                            Name = "أخصائي نسائية وتوليد",
                            NormalizedName = "Obstetrician-Gynecologist (OB-GYN)"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4632),
                            IsDeleted = false,
                            Name = "أخصائي أطفال",
                            NormalizedName = "Pediatrician"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4632),
                            IsDeleted = false,
                            Name = "أخصائي أورام",
                            NormalizedName = "Oncologist"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4633),
                            IsDeleted = false,
                            Name = "أخصائي كلى",
                            NormalizedName = "Nephrologist"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4634),
                            IsDeleted = false,
                            Name = "أخصائي جهاز هضمي",
                            NormalizedName = "Gastroenterologist"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4635),
                            IsDeleted = false,
                            Name = "أخصائي غدد صماء",
                            NormalizedName = "Endocrinologist"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4636),
                            IsDeleted = false,
                            Name = "أخصائي جراحة تجميل",
                            NormalizedName = "Plastic Surgeon"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4637),
                            IsDeleted = false,
                            Name = "أخصائي جراحة دماغ وأعصاب",
                            NormalizedName = "Neurosurgeon"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4638),
                            IsDeleted = false,
                            Name = "أخصائي تخدير",
                            NormalizedName = "Anesthesiologist"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4638),
                            IsDeleted = false,
                            Name = "أخصائي طب الأسرة",
                            NormalizedName = "Family Medicine Specialist"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4678),
                            IsDeleted = false,
                            Name = "أخصائي الطب النفسي",
                            NormalizedName = "Psychiatrist"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4679),
                            IsDeleted = false,
                            Name = "أخصائي أمراض معدية",
                            NormalizedName = "Infectious Disease Specialist"
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4680),
                            IsDeleted = false,
                            Name = "أخصائي أشعة",
                            NormalizedName = "Radiologist"
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4680),
                            IsDeleted = false,
                            Name = "أخصائي طب طوارئ",
                            NormalizedName = "Emergency Medicine Specialist"
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4681),
                            IsDeleted = false,
                            Name = "أخصائي روماتيزم",
                            NormalizedName = "Rheumatologist"
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4682),
                            IsDeleted = false,
                            Name = "أخصائي صدرية",
                            NormalizedName = "Pulmonologist"
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4683),
                            IsDeleted = false,
                            Name = "أخصائي طب مهني",
                            NormalizedName = "Occupational Medicine Specialist"
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4684),
                            IsDeleted = false,
                            Name = "أخصائي طب رياضي",
                            NormalizedName = "Sports Medicine Specialist"
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4684),
                            IsDeleted = false,
                            Name = "أخصائي أمراض الدم",
                            NormalizedName = "Hematologist"
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4685),
                            IsDeleted = false,
                            Name = "أخصائي علاج طبيعي",
                            NormalizedName = "Physiotherapist"
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4686),
                            IsDeleted = false,
                            Name = "أخصائي تغذية",
                            NormalizedName = "Nutritionist"
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 953, DateTimeKind.Local).AddTicks(4687),
                            IsDeleted = false,
                            Name = "أخصائي نطق وتخاطب",
                            NormalizedName = "Speech Therapist"
                        });
                });

            modelBuilder.Entity("Clinic_Booking.Entities.SubscriptionPackage.SubscriptionPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("DeleterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("EBooking")
                        .HasColumnType("boolean");

                    b.Property<bool>("EPayments")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("MakeOffers")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxActiveOffers")
                        .HasColumnType("integer");

                    b.Property<int>("MaxClinics")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDailyAppointments")
                        .HasColumnType("integer");

                    b.Property<int>("MaxWeeklyDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("ModifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<bool>("ShowMessages")
                        .HasColumnType("boolean");

                    b.Property<bool>("ShowReviews")
                        .HasColumnType("boolean");

                    b.Property<decimal>("YearlyPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPackages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 955, DateTimeKind.Local).AddTicks(1260),
                            EBooking = false,
                            EPayments = false,
                            IsDeleted = false,
                            MakeOffers = false,
                            MaxActiveOffers = 0,
                            MaxClinics = 1,
                            MaxDailyAppointments = 15,
                            MaxWeeklyDays = 4,
                            Name = "أساسي",
                            NormalizedName = "Basic",
                            Price = 0m,
                            ShowMessages = false,
                            ShowReviews = false,
                            YearlyPrice = 0m
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 955, DateTimeKind.Local).AddTicks(1269),
                            EBooking = false,
                            EPayments = false,
                            IsDeleted = false,
                            MakeOffers = false,
                            MaxActiveOffers = 0,
                            MaxClinics = 2,
                            MaxDailyAppointments = 25,
                            MaxWeeklyDays = 5,
                            Name = "ذهبي",
                            NormalizedName = "Gold",
                            Price = 25m,
                            ShowMessages = false,
                            ShowReviews = true,
                            YearlyPrice = 250m
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 955, DateTimeKind.Local).AddTicks(1275),
                            EBooking = true,
                            EPayments = true,
                            IsDeleted = false,
                            MakeOffers = true,
                            MaxActiveOffers = 1,
                            MaxClinics = 3,
                            MaxDailyAppointments = 35,
                            MaxWeeklyDays = 6,
                            Name = "ألماس",
                            NormalizedName = "Diamond ",
                            Price = 35m,
                            ShowMessages = true,
                            ShowReviews = true,
                            YearlyPrice = 350m
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 1, 19, 34, 17, 955, DateTimeKind.Local).AddTicks(1277),
                            EBooking = true,
                            EPayments = true,
                            IsDeleted = false,
                            MakeOffers = true,
                            MaxActiveOffers = 2,
                            MaxClinics = 5,
                            MaxDailyAppointments = 1000,
                            MaxWeeklyDays = 7,
                            Name = "فاخر",
                            NormalizedName = "Premium",
                            Price = 45m,
                            ShowMessages = true,
                            ShowReviews = true,
                            YearlyPrice = 450m
                        });
                });

            modelBuilder.Entity("Clinic_Booking.Entities.User.AspNetUsers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("CreatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DeleterId")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ImageName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFirstLogin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLoginDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("ModifierId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4df64838-b86f-4e11-ad4e-1cbd49ab8df6"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f661c315-f2ce-4689-b7c3-d68fb3b64cc6",
                            CreatedAt = new DateTime(2026, 6, 1, 16, 34, 17, 890, DateTimeKind.Utc).AddTicks(2934),
                            EmailConfirmed = false,
                            IsDeleted = false,
                            IsFirstLogin = true,
                            IsLocked = false,
                            LastLoginDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LockoutEnabled = false,
                            NormalizedUserName = "SUPARADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAECMY1PZNaxv3pAAdr0pP/vgSs5k+ByU07WG0h2Bde2sai4WE4lZzOE7cFGrGQJkgBw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4e61dce9-ad03-4250-9b75-fa4912508dac",
                            TwoFactorEnabled = false,
                            UserName = "superadmin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Appointment.Appointment", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Clinic.Clinic", "Clinic")
                        .WithMany("Appointments")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clinic");

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.BookingOtpRequest.BookingOtpRequest", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Appointment.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Clinic.Clinic", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany("Clinics")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.ClinicException.ClinicException", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Clinic.Clinic", "Clinic")
                        .WithMany("Exceptions")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Doctor.Doctor", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Specialization.Specialization", "Specialization")
                        .WithMany()
                        .HasForeignKey("SpecializationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", "User")
                        .WithOne()
                        .HasForeignKey("Clinic_Booking.Entities.Doctor.Doctor", "UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Specialization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorAvailability.DoctorAvailability", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Clinic.Clinic", "Clinic")
                        .WithMany("Availabilities")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.Day.Day", "Day")
                        .WithMany()
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");

                    b.Navigation("Day");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorFeature.DoctorFeature", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany("DoctorFeatures")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.Feature.Feature", "Feature")
                        .WithMany("DoctorFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.DoctorSubscription.DoctorSubscription", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany("DoctorSubscriptions")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.SubscriptionPackage.SubscriptionPackage", "Package")
                        .WithMany()
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Package");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Message.Message", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Receiver")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Notification.Notification", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany("Notifications")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Payment.Payment", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Appointment.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Referral.Referral", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "InvitedDoctor")
                        .WithMany()
                        .HasForeignKey("InvitedDoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "InviterDoctor")
                        .WithMany()
                        .HasForeignKey("InviterDoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("InvitedDoctor");

                    b.Navigation("InviterDoctor");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Review.Review", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Appointment.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppoinmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Clinic_Booking.Entities.Doctor.Doctor", "Doctor")
                        .WithMany("Reviews")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Doctor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Role.AspNetRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.Role.AspNetRoles", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Clinic_Booking.Entities.User.AspNetUsers", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Clinic.Clinic", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Availabilities");

                    b.Navigation("Exceptions");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Doctor.Doctor", b =>
                {
                    b.Navigation("Clinics");

                    b.Navigation("DoctorFeatures");

                    b.Navigation("DoctorSubscriptions");

                    b.Navigation("Notifications");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Clinic_Booking.Entities.Feature.Feature", b =>
                {
                    b.Navigation("DoctorFeatures");
                });
#pragma warning restore 612, 618
        }
    }
}
